### PR TITLE
Removed slink stealth / disable cloak when firing behaviour

### PR DESCRIPTION
**Pull request by rajderks**
Please test the unit. I did it but i never understood cloak/stealth so not sure if working correctly :P

### CODE REVIEW

**Comment by Azraeel** [comment]
Sorry, I guess I didn't describe the issue that was relayed to me. PMC said he wanted the Slink to automatically reenable the Cloak when the cloak was disabled due to the weapon firing.

Currently the Slink does NOT reenable it's cloak after it's fired its weapon.

**Comment by rajderks** [comment]
This is beyond my abilities @Azraeel 

The onWeaponFired function gets hit, but even if i remove the if-statement it doesnt re-cloak. So i have no idea. 📦

**Comment by Azraeel** [comment]
this should work as intended for the original issue.

**Comment by Azraeel** [comment]
angryface....

**Review by Azraeel — APPROVED** [review]

**Pull request merged**
